-- PSMF Family — migration 12b: seed the roster with your original
-- WhatsApp birthday list. Run this ONCE, right after migration_12's
-- section runs successfully. All 152 names from the original list —
-- exact duplicates already removed.

insert into public.roster (full_name, birth_month, birth_day, anniversary_month, anniversary_day)
values
    ('Marianne Oyeneye', 12, 10, 11, 7),
    ('Adereti Itunu Deborah', 2, 27, null, null),
    ('Akinremi Ifeoluwa', 5, 26, null, null),
    ('Osundina Mayowa', 2, 18, null, null),
    ('Balogun Gbemi', 3, 4, null, null),
    ('Iduh Helen', 2, 27, null, null),
    ('Olaosebikan Emmanuel Abiodun', 1, 1, null, null),
    ('Oladele Mary Omolola', 12, 6, null, null),
    ('I.B. Kay', 10, 24, null, null),
    ('Adetunji Timothy', 6, 29, null, null),
    ('Oguntimehin Sarah Adefunke', 7, 25, null, null),
    ('Adebare Adeyemi', 8, 29, null, null),
    ('Oladipupo Anuoluwapo Opeyemi', 10, 29, null, null),
    ('Adeshina Oluwafunmilayo Esther Ayoadeleye', 4, 6, 11, 30),
    ('Adewunmi Zainab Adetutu', 12, 14, null, null),
    ('Olaleye Damilola Deborah', 2, 9, null, null),
    ('Richard Oluwafiifunmi Praise', 11, 4, null, null),
    ('Ojulari Moyo', 4, 25, null, null),
    ('Williams Blessing', 6, 1, null, null),
    ('Mofiyinfoluwa', 11, 3, null, null),
    ('Enearu Mabel Ayomide', 11, 24, null, null),
    ('Olakunle Gabriel', 10, 20, null, null),
    ('Eyinju Damilola', 11, 1, null, null),
    ('Ajense Bisi Philip', 11, 12, null, null),
    ('Hope Jay', 11, 27, null, null),
    ('Idara Duff', 2, 25, null, null),
    ('Sadiku Oluwatomiwa Excel', 11, 16, null, null),
    ('Ogunyomi Anuoluwapo Esther', 3, 27, 10, 25),
    ('Godiya Rabiu', 11, 7, null, null),
    ('Afuye Kehinde', 5, 20, null, null),
    ('Michael Esther Oluwatobiloba', 4, 23, null, null),
    ('Ojeniyi Omolola Tioluwanimi', 5, 21, null, null),
    ('Grace Boluwatife Ishola', 2, 23, null, null),
    ('Temitope Abosede Olugbodi', 2, 5, null, null),
    ('Babatunde Abiodun Emmanuel', 12, 18, null, null),
    ('Oloyede Kehinde Elizabeth', 3, 21, null, null),
    ('Ayoade Temitope', 5, 24, null, null),
    ('Adebayo Temitope Esther', 6, 20, null, null),
    ('Olujobade Ayomide', 7, 7, null, null),
    ('Femi Abiola', 2, 28, null, null),
    ('Oladejo Julius', 10, 6, 2, 7),
    ('Ajibola Abolaji Olalekan', 1, 5, null, null),
    ('Oluku Precious Oghenekevwe', 9, 7, null, null),
    ('Olatunji Hannah Mojisola', 6, 18, null, null),
    ('Clement Fasanya', 8, 3, null, null),
    ('Israel Olaonipekun', 5, 23, null, null),
    ('Adejumo Grace', 11, 29, null, null),
    ('Adeyemi Oluwakemisola', 5, 31, null, null),
    ('Oladipupo Mercy Ayomide', 11, 28, null, null),
    ('Akinwemoye Temiloluwa', 7, 23, null, null),
    ('Ajumo Funmilayo Victoria', 1, 4, null, null),
    ('Adereti Mercy', 9, 7, null, null),
    ('A. A. Osazee', 8, 22, null, null),
    ('Ogunnaike Blessing', 1, 4, 9, 9),
    ('Blessing Agboola', 11, 28, null, null),
    ('Alayande Zainab Eniola', 7, 21, null, null),
    ('A. A. Clement', 5, 28, null, null),
    ('Ayomide Onasiwo', 11, 28, null, null),
    ('Akinniyi Bridget', 5, 7, null, null),
    ('Obafunso Opeyemi Comfort', 7, 20, null, null),
    ('Samuel Grace Olufunke', 5, 12, null, null),
    ('Olaojo Yetunde Miracle', 8, 16, null, null),
    ('Ileli Stephen Egbo', 8, 23, null, null),
    ('Peter Patience Piolamah', 12, 1, null, null),
    ('Olukoya Gloria Tolulope', 10, 10, null, null),
    ('Praise Peter', 2, 21, null, null),
    ('Adesanya Olamilekan Samuel', 4, 14, null, null),
    ('Kemi Racheal Oluokun', 10, 1, null, null),
    ('Fadunsi Oluwasegun', 1, 19, null, null),
    ('Adejumo Victoria', 8, 7, null, null),
    ('Elizabeth Abosede Olawole', 4, 15, 4, 27),
    ('Otaoroju Opeyemi Ayomide', 7, 5, null, null),
    ('Aringbere Abiodun', 12, 31, null, null),
    ('Adetunji Success Oluwanifemi', 1, 21, null, null),
    ('Adedokun Omolara Rachael', 5, 10, null, null),
    ('Olorunda Olajumoke N.', 9, 23, 7, 20),
    ('Olarewaju Grace', 2, 8, null, null),
    ('Esoimeme Bernard B.', 5, 26, null, null),
    ('Oladesu Boluwatife Racheal', 10, 15, null, null),
    ('Abadunmi Caleb Ogoluwa', 8, 14, null, null),
    ('Ogude Oghenefego Franklin', 12, 28, null, null),
    ('Faith Oghenemarho Ebireri', 11, 5, null, null),
    ('Olaleye Maria', 9, 27, null, null),
    ('Adeyemi Ayoola Emmanuel', 12, 6, null, null),
    ('Adeyemo Opeyemi Hannah', 12, 8, null, null),
    ('Oluwapelumi Adegke', 3, 15, null, null),
    ('Oyalami Olajumoke', 8, 25, null, null),
    ('Akinola Olawumi Olayode', 11, 16, 12, 17),
    ('Omoyemi Olajumoke', 9, 13, null, null),
    ('Awujoola Esther Ayomide', 4, 9, null, null),
    ('Olanrewaju Kehinde Precious', 1, 25, null, null),
    ('Osanyinbi Deborah Aduragbemi', 1, 31, null, null),
    ('Aina Grace Oluwaseun', 4, 19, null, null),
    ('Adesina Oluwamodupe', 6, 5, null, null),
    ('Oluwatosin Oluwaseun', 3, 10, null, null),
    ('Meliga Glorialois Ufeli', 5, 27, null, null),
    ('Oyindunlola Opeyemi', 12, 29, null, null),
    ('Olawale Ilemobola', 5, 1, null, null),
    ('Odedeji Omolola', 9, 2, 7, 15),
    ('Vincent Bamidele', 1, 8, null, null),
    ('Eniola Opeyemi', 5, 27, null, null),
    ('Deborah Joseph', 9, 13, null, null),
    ('Adepoju Oluwaseun', 6, 13, null, null),
    ('Abolade Taiwo', 12, 5, null, null),
    ('Samuel Hellen Temitope', 2, 13, null, null),
    ('David Ejeagba', 11, 28, 12, 19),
    ('Awotidoye Omowumi', 12, 13, null, null),
    ('Taiwo Ayomide', 9, 21, null, null),
    ('Ogundare Funmilayo Elizabeth', 7, 22, null, null),
    ('Adetuyi Temilade Adekemi', 10, 7, null, null),
    ('Ayinde Adeniyi Samuel', 3, 6, null, null),
    ('Adedeji Blessing Oluwaferanmi', 9, 16, 4, 15),
    ('Agbaje Zainab Moromoke', 2, 26, null, null),
    ('Olawale Abayomi', 5, 1, null, null),
    ('Adegoke Esther Oluwafisayomi', 5, 3, null, null),
    ('Taiwo Adekunle', 6, 16, null, null),
    ('Alimi Bose Ayomikun', 9, 20, null, null),
    ('Esther Ajoke', 2, 17, null, null),
    ('Ogundele Samson Ayobami', 3, 28, null, null),
    ('Omonijo Iyanuoluwa Victoria', 10, 29, null, null),
    ('Adewunmi Boluwatife Nathanael', 5, 8, null, null),
    ('Adegunloye Adepeju Chidimma', 9, 12, null, null),
    ('Modupe Favour', 4, 30, null, null),
    ('Temitope Dorcas', 8, 25, null, null),
    ('Muhammed Moses', 3, 5, null, null),
    ('Aigbojare Taiye Joshua', 6, 27, null, null),
    ('Abiola Daniel', 4, 25, null, null),
    ('Adeleye Marvelous Oreofe', 6, 23, null, null),
    ('Owhojeheri Roseline', 9, 16, null, null),
    ('Itunuoluwa Omotosho', 1, 23, 3, 7),
    ('Adeniran Moses Adejumoh', 10, 7, null, null),
    ('Ojelabi Aderinsola', 4, 20, null, null),
    ('Adesola Oluwanifemi', 6, 16, null, null),
    ('Lasisi Kehinde Asanat', 1, 31, null, null),
    ('Joshua Oyewo', 4, 30, null, null),
    ('Favour Atiba', 4, 26, null, null),
    ('Adewale Flourish', 4, 16, null, null),
    ('Olaoye Olajumoke', 1, 26, 7, 20),
    ('Mayeloye Praise Sharon', 3, 16, null, null),
    ('Friday Clinton', 8, 26, null, null),
    ('Margaret Oluwayemisi Olutan', 10, 16, null, null),
    ('Akinola Dorcas Abimbola', 6, 20, null, null),
    ('Okeronbi Rosemary Oluwapelumi', 12, 17, null, null),
    ('Akinrolayo Adesola Nifemi', 6, 16, null, null),
    ('Grace Emmanuel', 6, 20, null, null),
    ('Olulaja James', 8, 24, 9, 20),
    ('Lemboye Oluwapelumi', 8, 1, null, null),
    ('Dennis Lydia', 5, 11, null, null),
    ('Oke', 5, 24, 5, 29),
    ('Prince Adebowale Michael-Mary Ajiboye', 3, 14, null, null),
    ('Mrs Olajumoke', 6, 13, 2, 28),
    ('Oguntegbe Tunbosun Christianah', 4, 19, null, null)
on conflict do nothing;
